config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'images#index'

	resources :images do
	  collection do
	    get :search
	  end
	end

end

app/models/image.rb
class Image < ActiveRecord::Base
	has_attached_file :imagefile, styles: {
    		thumb: '100x100>',
    		square: '200x200#',
    		medium: '300x300>'
  		}
	validates_attachment_content_type :imagefile, content_type: /\Aimage\/.*\Z/
	belongs_to :user
	has_many :images_tags
	has_many :tags, through: :images_tags

	# We're defining this to permit getting and setting tags on Images.
	
	def tag_names
		tags.map { |tag| tag.name }.join(' ')
	end
	
	# If you don't put "self" here, it assumes you mean a local variable.
	def tag_names=(names)
		self.tags = names.split(' ').map do |tag_name|
			Tag.new name: tag_name
		end
	end

	def self.search(query, user)
           user.images.select{|i| i.tag_names =~ /#{query}/ || i.description =~ /#{query}/ }
    end
end

# .where("self.tag_names LIKE :query OR description LIKE :query", query: "%#{query}%")

app/models/images_tag.rb
class ImagesTag < ActiveRecord::Base
	belongs_to :image
	belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :images_tags
	has_many :images, through: :images_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	before_filter :authenticate_user!, only: [ :new, :create, :edit, :update, :delete ]

# There is some magic in here we need to make sure works:
# 1) Tags need to find their way to where they need to go from the view, despite tags not
# being an actual part of the image model
# 2) We want to take the %FILENAME.EXT% uploaded from Paperclip and put it into
# @image.filename
# 3) Make sure the index only applies to the images that belong to the user
# 4) Does that :imagefile thing work the way I think it does for Paperclip?
# 5) Need to make search work
# 6) Implement Imgur API?

	def index
		if user_signed_in?
			@search = params[:search]
			if @search
				@images = Image.search(@search, current_user)
			else
				@images = current_user.images # This needs to be "where Image.user = logged_in_user" or something
			end
			
		else
			@images = nil
		end
	end

	def create
		@image = current_user.images.new(image_params)

		if @image.save
			redirect_to @image
		else
			render 'new'
		end
	end
	
	def new
		@image = Image.new
	end
	
	def edit
		@image = Image.find(params[:id])
	end
	
	def show
		@image = Image.find(params[:id])
	end
	
	def destroy
		@image = Image.find(params[:id])
  		@image.destroy
 
  		redirect_to root_path
	end
	
	def update
		@image = Image.find(params[:id])
		
		if @image.update(image_params)
			redirect_to @image
		else
			render 'edit'
		end
	end
	
	private
	
	def image_params
		params.require(:image).permit(:description, :tag_names, :imagefile)
	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/_search.html.erb
<%= form_tag images_path, :class => 'form-inline', method: 'get' do %>
  <div class="form-group">
      <%= text_field_tag 'search', @search, :class => "form-control" %>
      <%= submit_tag 'Search' %> 
  </div>
<% end %>

app/views/images/edit.html.erb
<h3>Edit Image Detail</h3>

<div class="container">
	<%= form_for @image, url: image_path(@image), multipart: true, method: :patch do |f| %>
		<div class="form-group">
			<%= f.label :description %>
			<%= f.text_area :description, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :tag_names %>
			<%= f.text_field :tag_names, class: 'form-control' %>
		</div>

		<%= f.submit 'Submit', class: 'btn btn-primary btn-lg' %>
	<% end %>
</div>

app/views/images/index.html.erb
<h3>Image Index</h3>

<section>
	<% if @images.nil? %>
		<article>No user logged in, or no images available.</article>
	<% else %>
	<%= render 'search' %>
		<% @images.each do |i| %>
			<article>
				<section>
					<header><%= link_to i.imagefile_file_name, i %> || <%= link_to "Edit Image", edit_image_path(i) %></header>
					<article><%= image_tag i.imagefile.url(:thumb) %></article>
				</section>
			</article>
		<% end %>
	<% end %>
</section>			

app/views/images/new.html.erb
<h3>Add Image from your Computer<h3>

<div class="container">
	<%= form_for @image, multipart: true do |f| %>
		<div class="form-group">
			<%= f.label :description %>
			<%= f.text_area :description, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label "Tags for Image (separated by spaces)" %>
			<%= f.text_field :tag_names, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label "Image to Upload" %>
			<%= f.file_field :imagefile, class: 'form-control' %>
		</div>
		<%= f.submit 'Submit', class: 'btn btn-primary btn-lg' %>
	<% end %>
</div>

app/views/images/show.html.erb
<h3>Image Detail</h3>
<div><%= image_tag @image.imagefile.url %></div>
<p><%= @image.description %></p>
<div>Tags: <%= @image.tag_names %></div>
<div>Right-click the image and pick "Copy Image Location" to paste a hotlink to the image anywhere!</div>
<div><%= link_to "Edit Image Description or Tags", edit_image_path %></div>
<div><%= link_to "Delete Image", image_path, method: :delete %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeHost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>AwesomeHost</h2>
<h2>           ... because SFTP is a PITA</h2>

<nav class = "navbar navbar-default">
	<div class = "navbar-header>
		<a class = "navbar-brand" href = "#">Where Do You Want To Go Today™?</a>
	</div>
	<ul class = "nav navbar-nav">
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Add New Image from your Computer", new_image_path %></li> 
        <% if user_signed_in? %>
        	<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
		<% else %>
			<li><%= link_to "Sign Up", new_user_registration_path %></li>
			<li><%= link_to "Sign In", new_user_session_path %></li>
		<% end %>
	</ul>
</nav>

<p class = 'notice'><%= notice %></p>
<p class = 'alert'><%= alert %></p>

<%= yield %>

</body>
</html>